language: go
go:
  - "1.17.6" 
# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
# branches:
#   only:
#     - master
install: 
  - wget hhttps://github.com/gohugoio/hugo/releases/download/v0.89.4/hugo_extended_0.89.4_Linux-64bit.deb

  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/CaiJimmy/hugo-theme-stack.git --depth=1 themes/stack
  

script:
  - hugo

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip_cleanup: true # 重要，不能省略
  local_dir: public # 静态站点文件所在目录
  # target_branch: master # 要将静态站点文件发布到哪个分支
  github_token: $GITHUB_TOKEN 
  fqdn: billguo.cc 
  keep_history: true # 是否保持target-branch分支的提交记录
  on:
    branch: main