language: go
go:
  - "1.10"  # 指定Golang 1.8
# Specify which branches to build using a safelist
# 分支白名单限制：只有 master 分支的提交才会触发构建
# branches:
#   only:
#     - master
install: 
  # 安装最新的hugo
  - wget https://github.com/gohugoio/hugo/releases/download/v0.57.1/hugo_0.57.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  # 安装主题
  - git clone https://github.com/xianmin/hugo-theme-jane.git --depth=1 themes/jane

script:
  # 运行hugo命令
  - hugo
# after_script:
  # - git clone "https://billguocs:${GITHUB_TOKEN}@${GH_REF}" gh-pages
  # - rm github-pages/public -rf
  # - cp ./public/* github-pages -rf
  # - cd github-pages
  # - git add .
  # - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # - git push --force --quiet "https://billguocs:${GITHUB_TOKEN}@${GH_REF}" master:master 
  # - git push --quiet "https://billguocs:${GITHUB_TOKEN}@${GH_REF}" master:master --tags
# env:
#  global:
#    - GH_REF: github.com:billguocs/billguocs.github.io.git
deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip_cleanup: true # 重要，不能省略
  local_dir: public # 静态站点文件所在目录
  # target_branch: master # 要将静态站点文件发布到哪个分支
  github_token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  fqdn: billguo.cc # 如果是自定义域名，此处要填
  keep_history: true # 是否保持target-branch分支的提交记录
  on:
    branch: master # 博客源码的分支