# This is a basic workflow to help you get started with Actions

name: deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        # with:
        #     submodules: true
        #     fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
            go-version: "^1.17.0"
      - run: go version

      - name: Hugo setup
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: "latest"
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true

      # - name: Build and Deploy
      #   run: |
      #     hugo -F --cleanDestinationDir  # 生成静态文件
      #     mkdir -p public  # 确保public文件夹存在
      #     cp -r public/* ./  # 复制生成的静态文件到仓库根目录

      - name: Build
        run: hugo --minify --gc

      - name: GitHub Pages action
        # You may pin to the exact commit or the version.
        # uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          # Set a SSH private key from repository secret value for pushing to the remote branch.
          # deploy_key: # optional
          # Set a generated GITHUB_TOKEN for pushing to the remote branch.
          # github_token: # optional
          # Set a personal access token for pushing to the remote branch.
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # Set a target branch for deployment.
          # publish_branch: # optional, default is gh-pages
          # Set an input directory for deployment.
          # publish_dir: # optional, default is public
          # Set an destination subdirectory for deployment.
          # destination_dir: # optional, default is 
          # # Set an external repository (owner/repo).
          # external_repository: # optional
          # # If empty commits should be made to the publication branch
          # allow_empty_commit: # optional, default is false
          # # If existing files in the publish branch should be not removed before deploying
          # keep_files: # optional, default is false
          # # Keep only the latest commit on a GitHub Pages branch
          # force_orphan: # optional, default is false
          # # Set Git user.name
          # user_name: # optional
          # # Set Git user.email
          # user_email: # optional
          # # Set a custom commit message with a triggered commit hash
          # commit_message: # optional
          # # Set a custom full commit message without a triggered commit hash
          # full_commit_message: # optional
          # # Set tag name
          # tag_name: # optional
          # # Set tag message
          # tag_message: # optional
          # # Enable the GitHub Pages built-in Jekyll
          # enable_jekyll: # optional, default is false
          # # An alias for enable_jekyll to disable adding .nojekyll file to a publishing branch
          # disable_nojekyll: # optional, default is false
          # # Set custom domain
          # cname: # optional
          # # Set files or directories to exclude from a publish directory.
          # exclude_assets: # optional, default is .github
          
